const { EmbedBuilder, AttachmentBuilder } = require('discord.js');
const db = require('../database/schema');
const config = require('../config');
module.exports = {
  name: 'ticket_transcript',
  async execute(interaction, client) {
    const t = db.prepare("SELECT * FROM tickets WHERE channel_id = ? AND status = 'open'").get(interaction.channel.id);
    if (!t) return interaction.reply({ embeds: [new EmbedBuilder().setDescription('Not an open ticket.').setColor(config.errorColor)], flags: 64 });
    await interaction.deferReply();
    let msgs = [], lastId = null, fetching = true;
    while (fetching) { const opts = { limit: 100 }; if (lastId) opts.before = lastId; const batch = await interaction.channel.messages.fetch(opts); if (batch.size === 0) fetching = false; else { msgs.push(...batch.values()); lastId = batch.last().id; } }
    msgs.reverse();
    const header = `Transcript for #${interaction.channel.name}\n${'='.repeat(50)}\n\n`;
    const lines = msgs.map(m => `[${m.createdAt.toLocaleString()}] ${m.author.tag}: ${m.content || '(embed/file)'}`);
    const file = new AttachmentBuilder(Buffer.from(header + lines.join('\n'), 'utf-8'), { name: `transcript-${interaction.channel.name}.txt` });
    interaction.editReply({ embeds: [new EmbedBuilder().setTitle(`Transcript — ${interaction.channel.name}`).setDescription(`Generated by <@${interaction.user.id}>`).setColor(config.infoColor).setTimestamp()], files: [file] });
  },
};
